import type { CucumberReport } from "./cucumber-types"

export const sampleReport: CucumberReport = [
  {
    id: "login-feature",
    keyword: "Feature",
    name: "Login de Usuario",
    description: "Verificar que el usuario puede iniciar sesion correctamente",
    uri: "features/login.feature",
    tags: [{ name: "@smoke" }],
    line: 1,
    elements: [
      {
        id: "login-feature;login-exitoso",
        keyword: "Scenario",
        name: "Login exitoso con credenciales validas",
        type: "scenario",
        tags: [{ name: "@smoke" }, { name: "@login" }],
        line: 5,
        steps: [
          { keyword: "Given ", name: "el usuario esta en la pagina de login", result: { status: "passed", duration: 1_200_000_000 }, line: 6 },
          { keyword: "When ", name: "ingresa el usuario 'admin' y password 'admin123'", result: { status: "passed", duration: 800_000_000 }, line: 7 },
          { keyword: "Then ", name: "el sistema muestra el dashboard principal", result: { status: "passed", duration: 500_000_000 }, line: 8 },
        ],
      },
      {
        id: "login-feature;login-fallido",
        keyword: "Scenario",
        name: "Login fallido con credenciales invalidas",
        type: "scenario",
        tags: [{ name: "@login" }],
        line: 10,
        steps: [
          { keyword: "Given ", name: "el usuario esta en la pagina de login", result: { status: "passed", duration: 1_100_000_000 }, line: 11 },
          { keyword: "When ", name: "ingresa el usuario 'admin' y password 'wrong'", result: { status: "passed", duration: 900_000_000 }, line: 12 },
          { keyword: "Then ", name: "el sistema muestra mensaje de error", result: { status: "passed", duration: 300_000_000 }, line: 13 },
        ],
      },
      {
        id: "login-feature;bloqueo-cuenta",
        keyword: "Scenario",
        name: "Bloqueo de cuenta tras multiples intentos",
        type: "scenario",
        tags: [{ name: "@login" }, { name: "@security" }],
        line: 15,
        steps: [
          { keyword: "Given ", name: "el usuario esta en la pagina de login", result: { status: "passed", duration: 1_000_000_000 }, line: 16 },
          { keyword: "When ", name: "intenta login 5 veces con credenciales invalidas", result: { status: "passed", duration: 4_500_000_000 }, line: 17 },
          { keyword: "Then ", name: "la cuenta queda bloqueada por 15 minutos", result: { status: "failed", duration: 200_000_000, error_message: "Expected account to be locked but status was 'active'. Assertion failed at AccountPage:45" }, line: 18 },
        ],
      },
    ],
  },
  {
    id: "carrito-compras",
    keyword: "Feature",
    name: "Carrito de Compras",
    description: "Funcionalidades del carrito de compras",
    uri: "features/carrito.feature",
    tags: [{ name: "@ecommerce" }],
    line: 1,
    elements: [
      {
        id: "carrito-compras;agregar-producto",
        keyword: "Scenario",
        name: "Agregar producto al carrito",
        type: "scenario",
        tags: [{ name: "@ecommerce" }, { name: "@carrito" }],
        line: 5,
        steps: [
          { keyword: "Given ", name: "el usuario navega a la pagina de productos", result: { status: "passed", duration: 2_000_000_000 }, line: 6 },
          { keyword: "When ", name: "selecciona el producto 'Laptop Pro X'", result: { status: "passed", duration: 600_000_000 }, line: 7 },
          { keyword: "And ", name: "hace clic en 'Agregar al carrito'", result: { status: "passed", duration: 400_000_000 }, line: 8 },
          { keyword: "Then ", name: "el carrito muestra 1 producto", result: { status: "passed", duration: 350_000_000 }, line: 9 },
        ],
      },
      {
        id: "carrito-compras;eliminar-producto",
        keyword: "Scenario",
        name: "Eliminar producto del carrito",
        type: "scenario",
        tags: [{ name: "@ecommerce" }, { name: "@carrito" }],
        line: 11,
        steps: [
          { keyword: "Given ", name: "el carrito tiene 2 productos", result: { status: "passed", duration: 1_500_000_000 }, line: 12 },
          { keyword: "When ", name: "elimina el primer producto", result: { status: "passed", duration: 700_000_000 }, line: 13 },
          { keyword: "Then ", name: "el carrito muestra 1 producto", result: { status: "passed", duration: 300_000_000 }, line: 14 },
        ],
      },
      {
        id: "carrito-compras;aplicar-cupon",
        keyword: "Scenario",
        name: "Aplicar cupon de descuento",
        type: "scenario",
        tags: [{ name: "@ecommerce" }, { name: "@descuentos" }],
        line: 16,
        steps: [
          { keyword: "Given ", name: "el carrito tiene productos por $500", result: { status: "passed", duration: 1_200_000_000 }, line: 17 },
          { keyword: "When ", name: "aplica el cupon 'DESC20'", result: { status: "failed", duration: 800_000_000, error_message: "CouponService.apply() returned null - coupon 'DESC20' not found in database. NullPointerException at CouponService.java:112" }, line: 18 },
          { keyword: "Then ", name: "el total muestra $400", result: { status: "skipped" }, line: 19 },
        ],
      },
      {
        id: "carrito-compras;checkout",
        keyword: "Scenario",
        name: "Proceso de checkout completo",
        type: "scenario",
        tags: [{ name: "@ecommerce" }, { name: "@checkout" }],
        line: 21,
        steps: [
          { keyword: "Given ", name: "el carrito tiene productos seleccionados", result: { status: "passed", duration: 1_800_000_000 }, line: 22 },
          { keyword: "When ", name: "completa los datos de envio", result: { status: "passed", duration: 2_000_000_000 }, line: 23 },
          { keyword: "And ", name: "selecciona metodo de pago 'Tarjeta de credito'", result: { status: "passed", duration: 1_500_000_000 }, line: 24 },
          { keyword: "And ", name: "confirma la compra", result: { status: "passed", duration: 3_000_000_000 }, line: 25 },
          { keyword: "Then ", name: "recibe confirmacion de compra exitosa", result: { status: "passed", duration: 500_000_000 }, line: 26 },
        ],
      },
    ],
  },
  {
    id: "busqueda-productos",
    keyword: "Feature",
    name: "Busqueda de Productos",
    description: "Verificar que la busqueda de productos funciona correctamente",
    uri: "features/busqueda.feature",
    tags: [{ name: "@search" }],
    line: 1,
    elements: [
      {
        id: "busqueda-productos;busqueda-simple",
        keyword: "Scenario",
        name: "Busqueda simple por nombre",
        type: "scenario",
        tags: [{ name: "@search" }],
        line: 5,
        steps: [
          { keyword: "Given ", name: "el usuario esta en la pagina principal", result: { status: "passed", duration: 1_000_000_000 }, line: 6 },
          { keyword: "When ", name: "busca 'laptop'", result: { status: "passed", duration: 1_200_000_000 }, line: 7 },
          { keyword: "Then ", name: "se muestran resultados que contienen 'laptop'", result: { status: "passed", duration: 800_000_000 }, line: 8 },
        ],
      },
      {
        id: "busqueda-productos;busqueda-filtros",
        keyword: "Scenario",
        name: "Busqueda con filtros avanzados",
        type: "scenario",
        tags: [{ name: "@search" }, { name: "@filters" }],
        line: 10,
        steps: [
          { keyword: "Given ", name: "el usuario esta en la pagina de busqueda", result: { status: "passed", duration: 900_000_000 }, line: 11 },
          { keyword: "When ", name: "aplica filtro por precio '$100 - $500'", result: { status: "passed", duration: 600_000_000 }, line: 12 },
          { keyword: "And ", name: "aplica filtro por marca 'TechBrand'", result: { status: "passed", duration: 500_000_000 }, line: 13 },
          { keyword: "Then ", name: "se muestran solo productos que cumplen ambos filtros", result: { status: "passed", duration: 700_000_000 }, line: 14 },
        ],
      },
      {
        id: "busqueda-productos;sin-resultados",
        keyword: "Scenario",
        name: "Busqueda sin resultados",
        type: "scenario",
        tags: [{ name: "@search" }],
        line: 16,
        steps: [
          { keyword: "Given ", name: "el usuario esta en la pagina principal", result: { status: "passed", duration: 1_000_000_000 }, line: 17 },
          { keyword: "When ", name: "busca 'xyznonexistent123'", result: { status: "passed", duration: 1_100_000_000 }, line: 18 },
          { keyword: "Then ", name: "se muestra mensaje 'No se encontraron resultados'", result: { status: "passed", duration: 400_000_000 }, line: 19 },
        ],
      },
    ],
  },
  {
    id: "perfil-usuario",
    keyword: "Feature",
    name: "Perfil de Usuario",
    description: "Gestion del perfil de usuario",
    uri: "features/perfil.feature",
    tags: [{ name: "@profile" }],
    line: 1,
    elements: [
      {
        id: "perfil-usuario;editar-nombre",
        keyword: "Scenario",
        name: "Editar nombre de usuario",
        type: "scenario",
        tags: [{ name: "@profile" }],
        line: 5,
        steps: [
          { keyword: "Given ", name: "el usuario accede a su perfil", result: { status: "passed", duration: 1_300_000_000 }, line: 6 },
          { keyword: "When ", name: "cambia su nombre a 'Juan Perez'", result: { status: "passed", duration: 600_000_000 }, line: 7 },
          { keyword: "And ", name: "guarda los cambios", result: { status: "passed", duration: 800_000_000 }, line: 8 },
          { keyword: "Then ", name: "el perfil muestra 'Juan Perez'", result: { status: "passed", duration: 400_000_000 }, line: 9 },
        ],
      },
      {
        id: "perfil-usuario;cambiar-password",
        keyword: "Scenario",
        name: "Cambiar password",
        type: "scenario",
        tags: [{ name: "@profile" }, { name: "@security" }],
        line: 11,
        steps: [
          { keyword: "Given ", name: "el usuario accede a configuracion de seguridad", result: { status: "passed", duration: 1_100_000_000 }, line: 12 },
          { keyword: "When ", name: "ingresa password actual y nuevo password", result: { status: "passed", duration: 700_000_000 }, line: 13 },
          { keyword: "Then ", name: "el sistema confirma el cambio de password", result: { status: "failed", duration: 300_000_000, error_message: "TimeoutError: Password change confirmation not received within 10000ms. Server response timeout at SecurityController:89" }, line: 14 },
        ],
      },
      {
        id: "perfil-usuario;subir-avatar",
        keyword: "Scenario",
        name: "Subir foto de avatar",
        type: "scenario",
        tags: [{ name: "@profile" }, { name: "@upload" }],
        line: 16,
        steps: [
          { keyword: "Given ", name: "el usuario accede a su perfil", result: { status: "passed", duration: 1_200_000_000 }, line: 17 },
          { keyword: "When ", name: "selecciona una imagen de avatar", result: { status: "passed", duration: 500_000_000 }, line: 18 },
          { keyword: "And ", name: "confirma la subida", result: { status: "passed", duration: 2_500_000_000 }, line: 19 },
          { keyword: "Then ", name: "el avatar se actualiza correctamente", result: { status: "passed", duration: 600_000_000 }, line: 20 },
        ],
      },
    ],
  },
  {
    id: "notificaciones",
    keyword: "Feature",
    name: "Sistema de Notificaciones",
    description: "Verificar el sistema de notificaciones",
    uri: "features/notificaciones.feature",
    tags: [{ name: "@notifications" }],
    line: 1,
    elements: [
      {
        id: "notificaciones;recibir-notificacion",
        keyword: "Scenario",
        name: "Recibir notificacion de nueva orden",
        type: "scenario",
        tags: [{ name: "@notifications" }],
        line: 5,
        steps: [
          { keyword: "Given ", name: "el usuario tiene notificaciones habilitadas", result: { status: "passed", duration: 800_000_000 }, line: 6 },
          { keyword: "When ", name: "se genera una nueva orden", result: { status: "passed", duration: 1_500_000_000 }, line: 7 },
          { keyword: "Then ", name: "el usuario recibe notificacion push", result: { status: "passed", duration: 600_000_000 }, line: 8 },
        ],
      },
      {
        id: "notificaciones;marcar-leida",
        keyword: "Scenario",
        name: "Marcar notificacion como leida",
        type: "scenario",
        tags: [{ name: "@notifications" }],
        line: 10,
        steps: [
          { keyword: "Given ", name: "el usuario tiene 5 notificaciones sin leer", result: { status: "passed", duration: 900_000_000 }, line: 11 },
          { keyword: "When ", name: "abre la primera notificacion", result: { status: "passed", duration: 400_000_000 }, line: 12 },
          { keyword: "Then ", name: "la notificacion se marca como leida", result: { status: "passed", duration: 300_000_000 }, line: 13 },
          { keyword: "And ", name: "el contador muestra 4 sin leer", result: { status: "passed", duration: 200_000_000 }, line: 14 },
        ],
      },
    ],
  },
]
